# Generated by Django 5.0.4 on 2024-04-28 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_categoria', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Congelamento',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_congelamento', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('modo_preparo', models.TextField()),
                ('tempo_preparo', models.IntegerField()),
                ('dificuldade', models.CharField(max_length=1)),
                ('rendimento', models.IntegerField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='receitas/')),
            ],
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_refeicao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPrato',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_prato', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('codigo', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nome_alimento', models.CharField(max_length=255)),
                ('nome_categoria', models.CharField(max_length=255)),
                ('kcal', models.IntegerField()),
                ('porcao', models.CharField(max_length=255)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='alimentos/')),
                ('nome_categoria_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alimentos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(max_length=1)),
                ('congelamento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentos.congelamento')),
                ('nome_refeicao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentos.refeicao')),
            ],
        ),
        migrations.AddField(
            model_name='congelamento',
            name='tipo_prato_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentos.tipoprato'),
        ),
    ]
