# Generated by Django 5.0.3 on 2024-03-27 01:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id_alimento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=255)),
                ('kcal', models.IntegerField()),
                ('porcao', models.CharField(max_length=255)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='alimentos.alimento')),
            ],
        ),
    ]
