# Generated by Django 5.0.3 on 2024-03-28 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='alimento',
        ),
        migrations.AddField(
            model_name='alimento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='alimentos/'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentos.categoria'),
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unidade', models.CharField(max_length=5)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentos.alimento')),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('tempo_preparo', models.IntegerField()),
                ('dificuldade', models.CharField(max_length=1)),
                ('rendimento', models.IntegerField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='receitas/')),
                ('alimentos', models.ManyToManyField(through='alimentos.Ingrediente', to='alimentos.alimento')),
                ('tipo_prato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentos.tipoprato')),
            ],
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='receita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentos.receita'),
        ),
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=1)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentos.alimento')),
                ('refeicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentos.refeicao')),
            ],
        ),
    ]
