# Generated by Django 5.0.3 on 2024-03-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0002_refeicao_tipoprato_remove_categoria_alimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='alimentos',
            field=models.ManyToManyField(to='alimentos.alimento'),
        ),
        migrations.DeleteModel(
            name='Ingrediente',
        ),
    ]
